### ISSUE TITLE
`StdinCommand` discards stdin on an arg

### ISSUE THREAD

**Issue by max-sixty** [mitsuhiko/insta-cmd#2]
### What happened?

Thanks for `insta-cmd`! We recently started using it in PRQL, given how heavily we use `insta.

But here's an issue we hit in https://github.com/PRQL/prql/issues/2581 — if an arg is supplied to `StdinCommand`, it seems to discard `stdin` — note the second `stdout` output is empty:

### Reproduction steps

```rust
#[test]
fn test_insta_cmd() {
    let mut cmd = StdinCommand::new("cat", "foo");

    assert_cmd_snapshot!(cmd, @r###"
    success: true
    exit_code: 0
    ----- stdout -----
    foo
    ----- stderr -----
    "###);

    let mut cmd = StdinCommand::new("cat", "foo");

    assert_cmd_snapshot!(cmd.arg("-b"), @r###"
    success: true
    exit_code: 0
    ----- stdout -----

    ----- stderr -----
    "###);  # stdout here!
}

```

### Insta Version

insta = {version = "1.29", features = ["colors", "glob", "yaml"]}

### insta-cmd Version

insta-cmd = "0.2.0"

### rustc Version

1.64

### What did you expect?

Adding args keeps stdin

**Comment by max-sixty** [comment]
I spent some time working on this. I think the basic issue is that taking the stdin when creating `StdinCommand` is very difficult — we use `Deref` to then get the inner `Command`, and once we do anything to that, we lose the stdin.

Instead, how about:
```rust
assert_cmd_snapshot!(command, stdin="hello world");
```

On the downside, it breaks the convention of the `assert` macros being positional only.

Alternatively, are there any other symbols such as `@` that we could use?

**Comment by max-sixty** [comment]
If you're not sure, WDYT about me making `StdinCommand`'s fields public, or at least adding a `from_fields` constructor so we can construct a `StdinCommand` from a `command` & `stdin`?

(Because atm it's not really usable, unless I'm missing something)

**Comment by max-sixty** [comment]
@mitsuhiko I'm loath to "ping" you, given I know you manage a huge amount already, and how grateful I am for your contributions. 

But depending on whether this is maintained, we should probably move to [assert_cmd](https://docs.rs/assert_cmd/latest/assert_cmd/) (or maintain a fork of this temporarily?)

Or if you give the nod to a `from_fields` constructor, I'll put a PR in!

(I hope this is a reasonable message, feedback very welcome)

**Comment by mitsuhiko** [comment]
So I think something should be done here but I'm not sure what exactly. I will try to solve this now.

**Comment by max-sixty** [comment]
Apologies — you're correct it works when the `cmd.arg("-b")` is separate, and we're not using the _output_ of `cmd.arg("-b")`.

(I also agree that it's not ideal. And still think I won't be the first to be confused — the other PRQL-ers shared my view — but regardless it's very usable with the caveat above)

**Comment by mitsuhiko** [comment]
I'm definitely fixing it, but I am trying a few options now :)

**Comment by max-sixty** [comment]
Thanks a lot @mitsuhiko !

**Comment by konstin** [comment]
Could you please publish a new release? This breaks some very basic usages such as 

```rust
#[test]
fn echo() {
    assert_cmd_snapshot!(StdinCommand::new("echo", "hello world\n"));
}
```

**Comment by mitsuhiko** [comment]
Done now.

**Comment by max-sixty** [comment]
Thank you!

FYI for anyone who wants examples — https://github.com/PRQL/prql/pull/3435

**Comment by konstin** [comment]
Thank you!
