### ISSUE TITLE
Snapshots via `cargo run`

### ISSUE THREAD

**Issue by cnpryer** [mitsuhiko/insta-cmd#8]
Is there a reason to target the binary directly and not sit on top of `cargo run`?

**Comment by simonsan** [comment]
You can even target the build test binary directly with `Command::new(env!("CARGO_BIN_EXE_<name>")).args([])` where `<name>` is the `[[bin]]` name.

@mitsuhiko Probably worth to change here: https://docs.rs/insta-cmd/latest/insta_cmd/#testing-binaries 

As explained here: https://github.com/iqlusioninc/abscissa/issues/845

**Comment by cnpryer** [comment]
I don't remember when this was added, or if I had just missed it, but [`get_cargo_bin`](https://docs.rs/insta-cmd/latest/insta_cmd/fn.get_cargo_bin.html) works.

**Comment by simonsan** [comment]
> I don't remember when this was added, or if I had just missed it, but [`get_cargo_bin`](https://docs.rs/insta-cmd/latest/insta_cmd/fn.get_cargo_bin.html) works.

Ah, nice! :D
